language: ruby
bundler_args: --without development
before_install: sudo apt-get update && sudo apt-get install libaugeas-dev libxml2-dev
script: "bundle exec rake spec"
notifications:
  email: false
rvm:
  - 2.0.0
  - 1.9.3
  - 1.8.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
